trigger:
 - ver_1.0

pool: Flask

strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- scripts: |
   python3 -m pip install --upgrade pip setuptools wheel
   pip install -r requirements.txt
  displayName: 'Install dependencies'

- scripts: |
   pip install pytest pytest-azurepipelines
   pip install pytest-cov
   python3 -m pytest test_test1.py
  displayName: 'pytest' 

